openapi: 3.0.0
info:
  title: Job Archive
  description: API for an archive of job postings.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/SJhumili/JobArchiveAPI/1.0.0
  description: SwaggerHub API Auto Mocking
security:
- bearerAuth: []
tags:
- name: user
  description: Operations about user
- name: job
  description: Operations about job
paths:
  /user:
    get:
      tags:
      - user
      summary: Get user information
      description: An authenticated user be able to retrieve his or her information
      operationId: getuser
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                username: test
                email: test@test.com
                password: test
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
              example:
                username: test
                email: test@test.com
                password: test
        401:
          description: Access token is missing or invalid
    put:
      tags:
      - user
      summary: Update user profile
      description: An authenticated user be able to update information.
      operationId: updateuser
      requestBody:
        description: Updated user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              username: test
              email: test@test.com
              password: test
        required: true
      responses:
        200:
          description: User data successfully updated.
        default:
          description: Access token is missing or invalid
    delete:
      tags:
      - user
      summary: Delete user
      description: User be able to delete profile.
      operationId: deleteUser
      responses:
        200:
          description: Your profile deleted successfully.
        401:
          description: Access token is missing or invalid
  /user/signup:
    post:
      tags:
      - user
      summary: Create user
      description: User be able to sign up with username, password, email. After sign up backend will send token to email.
      operationId: signupuser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              name: test
              email: test@test.com
              password: test
        required: true
      responses:
        200:
          description: New user successfully created.
        default:
          description: The eamil is using by someone else.
      security: []
  /user/login:
    post:
      tags:
      - user
      summary: Login with username(email) and password
      description: Logs user into the system and server will respond user's access-token
      operationId: loginUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
        required: true
      responses:
        200:
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              style: simple
              explode: false
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              style: simple
              explode: false
              schema:
                type: string
                format: date-time
          content:
            application/xml:
              schema:
                type: string
                example: pong
            application/json:
              schema:
                type: string
                example: pong
        400:
          description: Invalid username/password supplied
  /user/logout:
    get:
      tags:
      - user
      summary: Logs out current logged in user
      operationId: logoutUser
      responses:
        200:
          description: User successfully log out.
        401:
          description: Access token is missing or invalid
  /validateEmail:
    get:
      tags:
      - user
      summary: Confirm user's email address
      operationId: confirmemail
      parameters:
      - name: token
        in: query
        description: this token is from backend after sign up
        required: true
        style: form
        explode: true
        schema:
          type: string
        example: awevbbrntye2y53n5467xcvbn35u7mu3456
      responses:
        200:
          description: Email address has been confirmed.
        default:
          description: Something went wrong
  /addjoblink:
    post:
      tags:
      - job
      summary: Post a link
      description: An authenticated user be able to post a link
      operationId: addjoblink
      requestBody:
        description: Job url
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Loginrequest'
        required: true
      responses:
        200:
          description: Job link added successfully.
        401:
          description: Access token is missing or invalid
  /joblinks:
    get:
      tags:
      - job
      summary: Get Job lists
      description: An authenticated user be able to retrieve joblinks
      operationId: getjoblinks
      parameters:
      - name: type
        in: query
        description: if type='all' user be able to retrieve all jobads but not 'all' user will retrieve his own posted jobads
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: all
          enum:
          - all
          - mine
      responses:
        200:
          description: Job links
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: '[http://example.com/job1, http://example.com/job2]'
        401:
          description: Access token is missing or invalid
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
      xml:
        name: User
    Loginrequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    body:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
